### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by DougVonMoser** [nrod80/seat-optimization#1]
Sweet work on the first algo!

I threw in a simple average file that can tell us the average of the cost of the algorithm ran a number of times. Really basic stuff for now but wanted to keep the momentum going.

**Comment by nrod80** [comment]
sweet! go ahead and push it up

**Comment by DougVonMoser** [comment]
yea it should be its own branch. stop wasting time with friends and loved ones and check it out!

**Comment by DougVonMoser** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/7258102-133915322_3-s1-v1.png?transparent=1&width=246)
